
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('sayings').del()
    .then(function () {
      // Inserts seed entries
      return knex('sayings').insert([
        {saying: 'Bless Your Heart', description: "It can be deployed sincerely, but if you’re hearing “bless your heart” in the South, it probably has an edge to it. It’s almost always accompanied by a good-natured, perhaps slightly exasperated, shake of the head. Don’t worry, though, everyone hears this every now and again."},
        {saying: 'Fixin\' To', description: "I’m fixin’ to tell you that this phrase is as Southern as sweet tea. When you’re fixin’ to do something, it’s going to happen, but you also may decide to take your sweet time. "},
        {saying: "It Doesn’t Amount to a Hill of Beans", description: "In the South, a hill of beans is its own measuring stick. Whether you’re talking about volume or value, a hill of beans isn’t worth much. That means whatever you’re talking about is worth less than very little."},
        {saying: "It's Blowin' Up a Storm", description: "If you’ve ever been caught in a summer storm, you know that you can feel, smell, and see a storm blowin’ up across the wide Southern skies. These skies can darken at a moment’s notice, and summer afternoons often see winds churning and heavy rain clouds blowing in to cool that Southern summer heat. "},
        {saying: "More Than Carter’s Got Little Pills", description: "This one originates from the 19th century, when Carter Products marketed “Little Liver Pills” across the country. Apparently Carter had a great many pills, because the phrase found its way into the Southern vocabulary. You may still hear it if you stop into a country store."},
        {saying: "Over Yonder", description: "When you’re in the South, “over yonder” is a distant direction—any direction. The phrase may be accompanied by a gesture indicating north, south, east, or west. Over yonder down the road. Over yonder past the cotton field. Over yonder toward the water tower. This phrase can be intensified by the addition of the word “way,” as in “way over yonder.” "},
        {saying: "Madder Than a Wet Hen", description: "Have you ever seen a wet hen? If so, you know that being madder than a wet hen is very mad indeed."},
        {saying: "'Til the Cows Come Home", description: "Settle in, because whatever we’re talking about is going to take all day. Cows aren’t known for their speed, and they are usually out and about, wandering until feeding time. Farmers know that if you do something ‘til the cows come home, it’s going to take all day. "},
        {saying: "If I Had My Druthers", description: "“Druthers” roughly translates to “I would rather,” meaning, “If had things my way…” The phrase is celebrated in song in the hilarious, Southern-inspired Broadway musical Li’l Abner, in which the title character sings “If I had my druthers, I'd druther have my druthers than anything else I know.” And really, wouldn’t we all druther have our druthers?"},
        {saying: "I Reckon", description: "I reckon “I reckon” can replace any number of phrases, such as: I guess, I suppose, I think, and I imagine. It is a quintessential Southern phrase, said by friends and family on porches and in rocking chairs all across the South. "},
        {saying: "Pretty as a Peach", description: "This is a high compliment in the South, since Southern states are known for their peaches. In fact, Georgia and South Carolina produce more peaches than any other states in the South. And of course, there’s nothing prettier than a warm summer day picking peaches in the sunshine."},
        {saying: "Full As A Tick", description: "If you’ve just had a big Southern lunch, complete with cornbread, collard greens, and pecan pie, you’re definitely full as a tick. It’s a vivid phrase, and it’s an accurate one too. "},
        {saying: "If the Creek Don't Rise", description: "Translated, this means: “We’ll be there unless something out of our control stops us.” Unlike the United States Postal Service, whose motto proclaims “Neither snow nor rain nor heat nor gloom of night” will keep them from their routes, sometimes a Southern visit is thwarted by a rising creek or other unexpected bump in the road."},
        {saying: "Worn Slap Out", description: "When you’re exhausted in an I’m-so-beat-I-can’t-go-on kind of way, you’re definitely worn slap out. It is a physical and mental state a few degrees past weary and just this side of dog-tired. It happens often during a Southern summer, when the heat rises and the temperatures shoot past 100."},
        {saying: "Hold Your Horses", description: "Stop right there! This one may be self-explanatory, but we can imagine it originating back in the days of stagecoaches, when horse-and-buggy pairs filled the streets. If you hear this one, it’s best to slow down."},
        {saying: "Well, I Declare", description: "A multipurpose Southernism. If you use this phrase, you could be declaring any number of things: surprise, dissent, happiness. The only requirement is that you declare it loud and proud."},
        {saying: "...as All Get Out", description: "“All get out” finds its way into Southern phrases constantly, and it intensifies any statement. I was surprised as all get out. It was bad as all get out. Anything to the degree of “all get out” is something to talk about."},
        {saying: "No Bigger Than a Minnow in a Fishing Pond", description: "When you arrive on the banks of the fishing pond on Saturday mornings, you’re hoping for a good catch—enough big catfish and bream to fry up for the family on Saturday night. If you find only minnows, though, they look even smaller compared to the heavy catch you hoped for. No bigger than a minnow in a fishing pond is as tiny as can be. "},
        {saying: "Heavens to Betsy", description: "An exclamation—of surprise, anger, happiness, really any emotion—that is appropriate in nearly every Southern scenario."},
        {saying: "Hush Your Mouth", description: "Grandma might whisper this one over her hymnal if she sees you cutting up in church on Sunday morning. We admit that we’ve heard this Southernism more than once."},
        {saying: "Too Big for His Britches", description: "Unarguable Southern criticism. Translated, it means, “He sure does think a lot of himself.” If you hear this one, you should probably pause a moment. Southerners tell it like it is—no matter what it is—so think of this as a learning moment."},
        {saying: "She's Got Gumption", description: "Gumption is spirit, courage, spunk, boldness, and initiative. If someone tells you that you’ve got gumption, you should thank them, and then walk a little taller, because you’ve received a lovely Southern compliment. Southerners adopted this phrase wholeheartedly from its early usages in 1700s England and Scotland (where it meant “common sense”). In the 1900s, the word evolved, taking on a Southern spin as well as new meanings such as “courage” and “get-up-and-go.”"},
        {saying: "Can't Never Could", description: "Positive thinking, Southern style. If you think you can’t, you won’t be able to accomplish something, but if you think you can, you’ll succeed. We like to read this as one of the greatest Southern encouragements, but, like most of these phrases, you can use it however you’d like."},
        {saying: "Well, I S'wanee", description: "Instead of “Well, I swear,” Southerners have adopted a geographically inspired alternative. “Well I s’wanee” evokes the Southern Suwannee River. Or, depending on where you live, it could be Sewanee, the small college town in Tennessee. "},
      ]);
    });
};
